services:
  startgenerate:
    build: .
    image: startgenerate-service:latest
    container_name: startgenerate-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8082:8082"   # local-only tetap terjaga (cuma loopback host)
    networks:
      - jadwal-network          # supaya bisa diakses container Java lewat nama container

networks:
  jadwal-network:
    external: true
